#!/bin/bash

# Quick setup script for the cookiecutter template

echo "🚀 Cookiecutter Python Project Setup"
echo "===================================="
echo ""
echo "This template creates Python projects with automatic Cursor IDE rules integration."
echo ""
echo "Two-Repo Model:"
echo "  - Cursor rules live in a separate repository"
echo "  - Added to projects as a Git submodule"
echo "  - Easy updates across all projects"
echo ""
echo "Before using this template:"
echo ""
echo "1. Create a cursor-rules repository:"
echo "   mkdir cursor-rules && cd cursor-rules"
echo "   mkdir -p .cursor/rules"
echo "   # Add your .mdc files to .cursor/rules/"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial cursor rules'"
echo "   git remote add origin https://github.com/your-org/cursor-rules.git"
echo "   git push -u origin main"
echo ""
echo "2. Update cookiecutter.json with your cursor_rules_repo URL"
echo ""
echo "3. Use the template:"
echo "   cookiecutter /Users/hua/Documents/codes_private/cookiecutter-python-project"
echo ""
echo "📋 Template Features:"
echo "   ✓ Automatic Git initialization"
echo "   ✓ Cursor rules as Git submodule"
echo "   ✓ Makefile with rule management commands"
echo "   ✓ Python project structure (src/, tests/)"
echo "   ✓ Pre-configured .gitignore"
echo "   ✓ Basic pytest setup"
echo ""
echo "📚 After project generation:"
echo "   make update-cursor-rules  - Pull latest rules"
echo "   make push-cursor-rule-edits - Push rule changes"
echo ""
