#!/bin/bash

# Quick setup script for the cookiecutter template

echo "🚀 Cookiecutter Python Project Setup"
echo "===================================="
echo ""
echo "This template creates Python projects with automatic Cursor IDE rules integration."
echo ""
echo "Before using this template, you should:"
echo ""
echo "1. Create a cursor-rules repository (if you don't have one):"
echo "   - The template includes a complete set of cursor rules"
echo "   - Copy them from {{cookiecutter.project_slug}}/.cursor/rules/"
echo "   - Create a new GitHub repo called 'cursor-rules'"
echo "   - Push the rules to your repository"
echo ""
echo "2. Update the cookiecutter.json file:"
echo "   - Set the default cursor_rules_repo URL to your repository"
echo ""
echo "3. Test the template locally:"
echo "   cookiecutter /Users/hua/Documents/codes_private/cookiecutter-python-project"
echo ""
echo "📋 Template Features:"
echo "   ✓ Automatic Git initialization"
echo "   ✓ Cursor rules as Git submodule"
echo "   ✓ Python project structure (src/, tests/)"
echo "   ✓ Makefile with common tasks"
echo "   ✓ Pre-configured .gitignore"
echo "   ✓ Basic pytest setup"
echo ""
echo "📚 Cursor rules are included in: {{cookiecutter.project_slug}}/.cursor/rules/"
echo ""
